config/routes.rb
SoupStash::Application.routes.draw do
  get "front_page/index"

  root :to => "front_page#index"

  devise_for :users

  resources :users do
    resources :players
  end
  match 'players/search' => 'players#search', :via => :get

  resources :games

  match 'tournament-0.13' => 'games#tourney_0_13', :via => :get
  match 'tournament-0.14' => 'games#tourney_0_14', :via => :get

  match ':action' => 'static#:action'

end

app/models/player.rb
class Player
  include Mongoid::Document

  paginates_per 27
  
  field :for_game, :type => String # Possibly unnecessary/implied?
  field :name,     :type => String

  field :created_at, :type => Time, :default => -> { Time.now }
  
  belongs_to  :user
  has_many    :games
  field :_id, :type => String, :default => -> { "%s-%s" % [name, for_game] }

  def basic_totals
    totals = Game.collection.aggregate(
      { '$match' => { 'character' => name } },
      { '$group' => {'_id' => '$character', 'played' => { '$sum' => 1 }, 'turns' => { '$sum' => '$turns' }, 'kills' => { '$sum' => '$kill_total' }, 'gold' => { '$sum' => '$gold_found' }, 'xls' => { '$sum' => '$xl' }, 'score' => { '$sum' => '$score' } } }
    ).first
    # Don't count the XL1 every game starts with
    totals['xls'] -= totals['played']
    return totals
  end

  def favourites # TODO Take time/version/etc as options
    return {} if Game.count == 0

    rbg_list = Game.collection.aggregate(
      { '$match' => { 'character' => name } },
      { '$group' => {'_id' => { 'race'=> '$race', 'background' => '$background', 'god' => '$god' }, 'count' => { '$sum' => 1 } } }
    )
    return {} if rbg_list.empty?

    faves = { race: {}, background: {}, god: {} }

    # It feels like this could be done by MongoDB:
    # http://stackoverflow.com/q/16633669/2398559
    rbg_list.each do |rbg|
      count = rbg['count']
      %w{race background god}.each do |col|
        val = rbg['_id'][col]
        next unless val && val.length > 0
        sym = col.to_sym
        faves[sym].key?(val) ? (faves[sym][val] += count) : (faves[sym][val] = count)
      end
    end

    return faves
  end

  def worst
    game = Game.collection.aggregate(
      { '$match'  => { 'character' => name, 'won' => false } },
      { '$project'=> { 'score' => 1, 'killer' => 1 } },
      { '$sort'   => { 'score' => -1 } },
      # Hope to find something in the first 20.
      { '$limit'  => 20 }
    )

    # Hack to avoid doing "killer != nil" in mongo which involves a
    # sequential scan and therefore is SLOW for anyone with a large
    # number of games.
    the_worst = game.find{|g| g['killer'] && g['killer'].length > 0}

    return the_worst ? Game.find(the_worst['_id']) : Game.first
  end

  def nemeses
    return {} if Game.count == 0

    result = Game.collection.aggregate(
      { '$match' => { 'character' => name } },
      { '$group' => {'_id' => '$killer', 'count' => { '$sum' => 1 } } },
      # Cheaper to do after the grouping.
      { '$match' => { '_id' => { '$ne' => nil } } },
      { '$sort'  => { 'count' => -1 } }
    )

    return {} if result.empty?

    result.each{|n| n['killer'] = n.delete('_id')}

    return result
  end
end

app/controllers/players_controller.rb
require_dependency 'collate/game'
require 'hashie'

class PlayersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :search]

  # GET /players
  # GET /players.json
  def index
    # TODO
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    # Needed for deep link generation.
    @user   = User.find(params[:user_id])

    @player = Player.find(params[:id])
    name    = @player.name

    games = Collate::Game.new(result_set: Game.for(name)).filter_and_sort({
        params:       params,
        order:        'desc',
        sort_default: :end_time
      })

    @games  = games.page(params[:page]).per(10)
    @totals = Hashie::Mash.new(@player.basic_totals)
    @faves  = @player.favourites

    @gkills  = Game.where(killer: "#{name}'s ghost").count
    @worst   = @player.worst
    @nemeses = @player.nemeses

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = current_user.players.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = current_user.players.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to [@player.user, @player], notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: url }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to [@player.user, @player], notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to user_players_url }
      format.json { head :no_content }
    end
  end

  # respond_to :json
  def search
    @players = Player.where(name: /^#{Regexp::quote(params[:q])}/i)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%# XXX Be explicit because I renamed controller (I guess?) %>
<%= form_for(@player, :url => { :action => 'create' }) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :for_game %><br />
    <%= f.select(:for_game, options_for_select([
      ['Dungeon Crawl Stone Soup', 'crawl'],
      ['Brogue', 'brogue']
    ])) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', [@player.user, @player] %> |
<%= link_to 'Back', user_players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>For game</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.for_game %></td>
    <td><%= player.name %></td>

    <td><%= link_to 'Show', [@user, player] %></td>
    <td><%= link_to 'Edit', edit_user_player_path(@user, player) %></td>
    <td><%= link_to 'Destroy', [@user,player], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_user_player_path(@user, @player) %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', user_players_path %>

app/views/players/search.html.erb
<% if @players.length > 0 %>
<h1>Found <%= @players.length %> <%= 'player'.pluralize(@players.length) %> matching &quot;<%= params[:q] %>&quot;</h1>
<ul class=unstyled>
<% for p in @players %>
  <li><%= link_to p.name, user_player_path(p.user, p) %></li>
<% end %>
</ul>
<% else %>

Didn't find any players matching &quot;<%= params[:q] %>&quot;
<% end %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='span8'>
    <h1><%= link_to @player.name, user_player_path(@user, @player) %></td>
    <h4>Recent games</h4>
    <div class='game-listing'>
      <%= render 'shared/selections' %>
      <table class='table table-striped table-condensed'>
        <thead>
          <tr>
            <th><%= link_to_with 'Score', 'sort' => 'score' %></th>
            <th>Character</th>
            <!-- TODO Only show valid options! -->
            <th><%= render 'shared/combo_filter' %></th>
            <th><%= render partial: 'shared/column_filter',
                    locals: { column: 'God', filterables: DCSS.gods, param: 'god' }
                    %>
            </th>
            <th><abbr title="Experience Level">XL</abbr></th>
            <th>Killer</th>
          </tr>
        </thead>
        <tbody>
          <% for game in @games.desc(:end_time).limit(10) %>
          <tr>
	    <td><%= link_to number_with_delimiter(game.score), game_path(game) %>
	      <% if game.won %><i class="icon-star" title="Won!"></i><% end %></td>
            <td><%= game.character %> the <%= game.title %></td>
            <td><%= link_to_with(game.race, 'race' => game.race) %>
                <%= link_to_with(game.background, 'background' => game.background) %></td>
            <td><%= link_to_with(game.god || 'None', 'god' => game.god) %></td>
            <td><%= game.xl %></td>
	    <td><%= game.ending_str %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @games %>
    </div>
  </div>

  <div class='span4'>
    <h4>Totals</h4>
    <dl class="dl-horizontal">
      <dt>Games played</dt><dd><%= number_with_delimiter(@totals.played || 0) %></dd>
      <dt>Score total</dt> <dd><%= number_with_delimiter(@totals.score || 0) %></dd>
      <dt>Total kills</dt> <dd><%= number_with_delimiter(@totals.kills || 0) %></dd>
      <dt>Turns used</dt>  <dd><%= number_with_delimiter(@totals.turns || 0) %></dd>
      <dt>Gold found</dt>  <dd><%= number_with_delimiter(@totals.gold || 0) %></dd>
      <dt>XP levelled</dt> <dd><%= number_with_delimiter(@totals.xls || 0) %></dd>
    </dl>
    <% unless @games.empty? %>
    <h4>Favourites</h4>
    <dl class="dl-horizontal">
      <% for fave in %w{race background god} %>
      <% next if @faves[fave.to_sym].empty? %>
      <dt><%= fave.titleize %></dt>
      <dd>
	<ul class='unstyled favourites-list'>
	<% top_faves = @faves[fave.to_sym].sort_by{|_,t| -t}[0 .. 2]
	   for fave, total in top_faves %>
	  <li><%= fave %> x <em><%= total.to_i %></em>
	<% end %>
	</ul>
      </dd>
      <% end %>
    <% end %>

    <h4>Premature endings</h4>
    <dl>
      <% if @gkills > 0 %>
      <dt>Ghost kills</dt><dd><%= link_to @gkills.to_s, games_path(killer: "#{@player.name}'s ghost") %></dd>
      <% end %>
      <dt>Worst enemy</dt><dd><%= link_to @worst.killer || @worst.terse_ending, game_path(@worst) %></dd>
      <dt>No. of deaths by</dt><dd>
        <ul id=nemeses class='unstyled more-less'>
          <% for mob in @nemeses %>
          <li class='toggle-display'><%= mob['killer'] %> x <em><%= mob['count'] %></em>
          <% end %>
        </ul>
        <% if @nemeses.length > 5 %>
        <button class='btn btn-small toggle-btn'>More/Less</button>
        <% end %>
    </dl>
  </div>
</div>